version: '3.7'
services:
  app:
    container_name: app.services
    build: .
    ports:
      - "9001:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - transaction
    volumes:
      - .:/app
  db:
    image: mysql
    container_name: db.service
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: wallet_transaction
    ports:
      - "3306:3306"
    networks:
      - transaction
  redis:
    image: redis
    container_name: redis.service
    ports:
      - "6379:6379"
    networks:
      - transaction
networks: 
  transaction:
    external: true